"""
Pydantic v2 schemas for the Contratos Menores ≤8 UIT module.

Covers the complete 9-step stepper workflow for minor contracting processes.
All response schemas are ORM-compatible via ``ConfigDict(from_attributes=True)``.

Business rules encoded here
----------------------------
- ``tipo_objeto`` must be one of the four values in ``constants.TIPOS_OBJETO``.
- ``estado`` for a contract must be one of ``constants.ESTADOS_CONTRATO_MENOR``.
- ``estado`` for a milestone step is one of ``"COMPLETADO"``, ``"EN_CURSO"``,
  ``"PENDIENTE"``.
- ``tipo_alerta`` for fraccionamiento is ``"CANTIDAD"`` or ``"MONTO"``.
"""

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# ContratoMenor — create / update / response
# ---------------------------------------------------------------------------


class ContratoMenorCreate(BaseModel):
    """Payload for registering a new minor contracting process.

    The ``codigo`` field (e.g. ``"CM-2026-001"``) is auto-generated by the
    service layer and must **not** be supplied by the caller.

    Attributes:
        descripcion: Description of the goods or services being contracted.
        tipo_objeto: Object type — one of ``"BIEN"``, ``"SERVICIO"``,
                     ``"OBRA"``, ``"CONSULTORIA"``.
        categoria: Grouping category used for fraccionamiento detection (e.g.
                   ``"MATERIAL_ESCRITORIO"``). Must be consistent across
                   related contracts from the same DDNNTT.
        ue_id: Foreign key to the UnidadEjecutora that owns this contract.
        meta_id: Foreign key to the MetaPresupuestal that funds it.
        monto_estimado: Estimated value in soles before quotations.
    """

    descripcion: str = Field(
        ...,
        min_length=5,
        max_length=1000,
        description="Descripción del bien o servicio a contratar.",
    )
    tipo_objeto: str = Field(
        ...,
        description=(
            "Tipo de objeto: 'BIEN', 'SERVICIO', 'OBRA' o 'CONSULTORIA'."
        ),
    )
    categoria: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description=(
            "Categoría usada para detectar fraccionamiento. "
            "Debe ser consistente con contratos relacionados."
        ),
    )
    ue_id: int = Field(..., ge=1, description="ID de la Unidad Ejecutora.")
    meta_id: int = Field(..., ge=1, description="ID de la Meta Presupuestal.")
    monto_estimado: float = Field(
        ...,
        gt=0,
        le=44_000.0,
        description="Monto estimado en soles (máx. S/44,000 = 8 UIT).",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "descripcion": "Adquisición de papel bond A4 80 gr. x 500 hojas",
                "tipo_objeto": "BIEN",
                "categoria": "MATERIAL_ESCRITORIO",
                "ue_id": 3,
                "meta_id": 12,
                "monto_estimado": 2_800.0,
            }
        }
    )


class ContratoMenorUpdate(BaseModel):
    """Partial update payload for an existing minor contracting process.

    All fields are optional; only supplied fields are applied.

    Attributes:
        estado: New process state.
        monto_ejecutado: Final executed amount once the order is paid.
        proveedor_id: FK to the winning Proveedor once awarded.
        n_orden: Service/purchase order number once issued.
        n_cotizaciones: Number of quotations obtained (minimum 3 required
                        by procurement regulation).
    """

    estado: str | None = Field(
        default=None,
        description=(
            "Estado del proceso: 'PENDIENTE', 'EN_PROCESO', "
            "'ORDEN_EMITIDA', 'EJECUTADO', 'PAGADO'."
        ),
    )
    monto_ejecutado: float | None = Field(
        default=None,
        gt=0,
        description="Monto ejecutado definitivo en soles.",
    )
    proveedor_id: int | None = Field(
        default=None,
        ge=1,
        description="ID del proveedor adjudicado.",
    )
    n_orden: str | None = Field(
        default=None,
        max_length=50,
        description="Número de orden de compra/servicio.",
    )
    n_cotizaciones: int | None = Field(
        default=None,
        ge=0,
        description="Cantidad de cotizaciones obtenidas.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "estado": "ORDEN_EMITIDA",
                "monto_ejecutado": 2_750.0,
                "proveedor_id": 7,
                "n_orden": "OC-2026-00345",
                "n_cotizaciones": 3,
            }
        }
    )


class ContratoMenorResponse(BaseModel):
    """Full representation of a ContratoMenor record with resolved labels.

    Includes denormalised strings (``ue_sigla``, ``meta_codigo``,
    ``proveedor_razon_social``) so the frontend does not need additional
    round-trips, plus the ordered list of milestone steps.

    Attributes:
        id: Primary key.
        codigo: Auto-generated process code, e.g. ``"CM-2026-001"``.
        anio: Fiscal year.
        descripcion: Description of goods or services.
        tipo_objeto: Object type string.
        categoria: Fraccionamiento category.
        estado: Current process state.
        monto_estimado: Estimated amount in soles.
        monto_ejecutado: Final executed amount (None until paid).
        n_orden: Order number (None until issued).
        n_cotizaciones: Number of quotations received.
        ue_id: FK to UnidadEjecutora.
        ue_sigla: Human-readable UE abbreviation (joined from UnidadEjecutora).
        meta_id: FK to MetaPresupuestal.
        meta_codigo: Human-readable meta code (joined from MetaPresupuestal).
        proveedor_id: FK to Proveedor (None until awarded).
        proveedor_razon_social: Supplier legal name (None until awarded).
        created_at: Record creation timestamp.
        updated_at: Last update timestamp.
        procesos: Ordered list of the 9 milestone steps.
    """

    id: int
    codigo: str | None
    anio: int | None
    descripcion: str | None
    tipo_objeto: str | None
    categoria: str | None
    estado: str | None
    monto_estimado: float | None
    monto_ejecutado: float | None
    n_orden: str | None
    n_cotizaciones: int

    # Denormalised join fields
    ue_id: int | None
    ue_sigla: str | None = Field(
        default=None,
        description="Sigla de la Unidad Ejecutora (join de unidad_ejecutora).",
    )
    meta_id: int | None
    meta_codigo: str | None = Field(
        default=None,
        description="Código de la Meta Presupuestal (join de meta_presupuestal).",
    )
    proveedor_id: int | None
    proveedor_razon_social: str | None = Field(
        default=None,
        description="Razón social del proveedor adjudicado (join de proveedor).",
    )

    created_at: datetime.datetime | None
    updated_at: datetime.datetime | None

    procesos: list[ContratoMenorProcesoResponse] = Field(
        default_factory=list,
        description="Pasos del proceso en orden (hitos 1–9).",
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": 1,
                "codigo": "CM-2026-001",
                "anio": 2026,
                "descripcion": "Adquisición de papel bond A4",
                "tipo_objeto": "BIEN",
                "categoria": "MATERIAL_ESCRITORIO",
                "estado": "ORDEN_EMITIDA",
                "monto_estimado": 2800.0,
                "monto_ejecutado": 2750.0,
                "n_orden": "OC-2026-00345",
                "n_cotizaciones": 3,
                "ue_id": 3,
                "ue_sigla": "INEI-LIMA",
                "meta_id": 12,
                "meta_codigo": "0012",
                "proveedor_id": 7,
                "proveedor_razon_social": "DISTRIBUIDORA XYZ S.A.C.",
                "created_at": "2026-01-15T08:00:00",
                "updated_at": "2026-02-01T14:30:00",
                "procesos": [],
            }
        },
    )


# ---------------------------------------------------------------------------
# ContratoMenorProceso — create / update / response
# ---------------------------------------------------------------------------


class ContratoMenorProcesoCreate(BaseModel):
    """Payload for adding a new milestone step to a minor contracting process.

    The ``orden`` (step number 1–9) is auto-calculated by the service as
    ``max(orden) + 1`` for the given contract; it must not be supplied.

    Attributes:
        hito: Name of the milestone step (e.g. ``"Requerimiento del área usuaria"``).
        area_responsable: Organisational area responsible for completing the step.
        dias_planificados: Planned working-day duration for the step.
        fecha_inicio: Planned start date for this step.
    """

    hito: str = Field(
        ...,
        min_length=3,
        max_length=200,
        description="Nombre del hito del proceso (ej. 'Requerimiento del área usuaria').",
    )
    area_responsable: str = Field(
        ...,
        min_length=2,
        max_length=50,
        description="Área organizacional responsable de este paso.",
    )
    dias_planificados: int = Field(
        ...,
        ge=1,
        le=365,
        description="Días hábiles planificados para completar el paso.",
    )
    fecha_inicio: datetime.date = Field(
        ...,
        description="Fecha planificada de inicio (ISO 8601 date).",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "hito": "Requerimiento del área usuaria",
                "area_responsable": "OTIN",
                "dias_planificados": 2,
                "fecha_inicio": "2026-01-15",
            }
        }
    )


class ContratoMenorProcesoUpdate(BaseModel):
    """Partial update for a milestone step — records completion.

    Attributes:
        fecha_fin: Actual completion date of the step.
        estado: New milestone state — ``"COMPLETADO"``, ``"EN_CURSO"``, or
                ``"PENDIENTE"``.
    """

    fecha_fin: datetime.date | None = Field(
        default=None,
        description="Fecha real de finalización del paso.",
    )
    estado: Literal["COMPLETADO", "EN_CURSO", "PENDIENTE"] | None = Field(
        default=None,
        description="Estado del hito: 'COMPLETADO', 'EN_CURSO' o 'PENDIENTE'.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "fecha_fin": "2026-01-17",
                "estado": "COMPLETADO",
            }
        }
    )


class ContratoMenorProcesoResponse(BaseModel):
    """Full representation of one milestone step in the stepper timeline.

    Attributes:
        id: Primary key.
        contrato_menor_id: FK to the parent ContratoMenor.
        orden: Sequential position 1–9.
        hito: Milestone name.
        area_responsable: Responsible area abbreviation.
        dias_planificados: Planned working-day duration.
        fecha_inicio: Planned start date.
        fecha_fin: Actual end date (None until completed).
        estado: Current step status.
    """

    id: int
    contrato_menor_id: int
    orden: int = Field(..., ge=1, le=9, description="Posición del paso (1–9).")
    hito: str
    area_responsable: str | None
    dias_planificados: int | None
    fecha_inicio: datetime.date | None
    fecha_fin: datetime.date | None
    estado: str | None

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": 1,
                "contrato_menor_id": 1,
                "orden": 1,
                "hito": "Requerimiento del área usuaria",
                "area_responsable": "OTIN",
                "dias_planificados": 2,
                "fecha_inicio": "2026-01-15",
                "fecha_fin": "2026-01-17",
                "estado": "COMPLETADO",
            }
        },
    )


# ---------------------------------------------------------------------------
# KPI summary card
# ---------------------------------------------------------------------------


class KpiContratosMenoresResponse(BaseModel):
    """Aggregate figures for the four KPI cards in the Contratos Menores dashboard.

    Attributes:
        total: Total number of minor contracts matching the current filters.
        monto_total: Sum of ``monto_estimado`` for all matching contracts.
        completados: Contracts in ``"PAGADO"`` or ``"EJECUTADO"`` state.
        en_proceso: Contracts in ``"EN_PROCESO"`` or ``"ORDEN_EMITIDA"`` state.
        porcentaje_avance: ``completados / total × 100`` (0 if no contracts).
        alerta_fraccionamiento: Number of active fraccionamiento alerts
                                detected for the selected year/UE.
    """

    total: int = Field(..., ge=0, description="Total de contratos menores.")
    monto_total: float = Field(..., description="Suma de montos estimados en soles.")
    completados: int = Field(..., ge=0, description="Contratos ejecutados o pagados.")
    en_proceso: int = Field(..., ge=0, description="Contratos en proceso u orden emitida.")
    porcentaje_avance: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Porcentaje de contratos completados (completados / total × 100).",
    )
    alerta_fraccionamiento: int = Field(
        ...,
        ge=0,
        description="Número de alertas de fraccionamiento activas.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "total": 84,
                "monto_total": 185_200.0,
                "completados": 52,
                "en_proceso": 20,
                "porcentaje_avance": 61.9,
                "alerta_fraccionamiento": 3,
            }
        }
    )


# ---------------------------------------------------------------------------
# Chart item
# ---------------------------------------------------------------------------


class GraficoContratoMenorItem(BaseModel):
    """Single data point for a minor-contracts distribution chart.

    Used for both the *by-estado* pie/bar chart and the *by-tipo_objeto*
    bar chart rendered in Recharts on the frontend.

    Attributes:
        label: Category label (estado or tipo_objeto string).
        cantidad: Number of contracts in this category.
        monto: Sum of ``monto_estimado`` for contracts in this category.
        porcentaje: Proportion of the total contract count (0–100).
    """

    label: str = Field(..., description="Etiqueta de la categoría (estado o tipo_objeto).")
    cantidad: int = Field(..., ge=0, description="Cantidad de contratos.")
    monto: float = Field(..., description="Suma de montos estimados en soles.")
    porcentaje: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Porcentaje sobre el total de contratos (0–100).",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "label": "ORDEN_EMITIDA",
                "cantidad": 15,
                "monto": 38_500.0,
                "porcentaje": 17.86,
            }
        }
    )


# ---------------------------------------------------------------------------
# Fraccionamiento alert
# ---------------------------------------------------------------------------


class FraccionamientoAlerta(BaseModel):
    """A detected fraccionamiento pattern requiring review.

    Two detection rules are applied:
    - **CANTIDAD** (Rule 1): Three or more contracts from the same DDNNTT
      for the same ``categoria`` in the same calendar month.
    - **MONTO** (Rule 2): Accumulated ``monto_estimado`` for the same
      ``categoria`` from the same DDNNTT exceeds 8 UIT (S/44,000) in the
      same calendar quarter.

    Attributes:
        ue_sigla: Abbreviation of the executing unit (DDNNTT).
        categoria: Contract category triggering the alert.
        mes: Month number (Rule 1) or quarter string like ``"Q1"`` (Rule 2).
        cantidad_contratos: Number of contracts in the suspicious grouping.
        monto_acumulado: Cumulative ``monto_estimado`` for the grouping.
        tipo_alerta: ``"CANTIDAD"`` or ``"MONTO"`` — the rule that fired.
        detalle: Human-readable explanation of the alert.
    """

    ue_sigla: str = Field(..., description="Sigla de la Unidad Ejecutora (DDNNTT).")
    categoria: str = Field(..., description="Categoría de contratación.")
    mes: str = Field(
        ...,
        description=(
            "Mes (nombre corto en español, ej. 'Ene') para CANTIDAD, "
            "o trimestre (ej. 'T1') para MONTO."
        ),
    )
    cantidad_contratos: int = Field(
        ..., ge=1, description="Contratos en el agrupamiento detectado."
    )
    monto_acumulado: float = Field(
        ..., description="Monto acumulado en soles del agrupamiento."
    )
    tipo_alerta: Literal["CANTIDAD", "MONTO"] = Field(
        ...,
        description="Regla disparada: 'CANTIDAD' (≥3 contratos/mes) o 'MONTO' (>8 UIT/trimestre).",
    )
    detalle: str = Field(
        ...,
        description="Descripción legible de la alerta para mostrar en pantalla.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ue_sigla": "INEI-AREQUIPA",
                "categoria": "MATERIAL_ESCRITORIO",
                "mes": "Ene",
                "cantidad_contratos": 4,
                "monto_acumulado": 11_200.0,
                "tipo_alerta": "CANTIDAD",
                "detalle": (
                    "INEI-AREQUIPA registró 4 contratos de 'MATERIAL_ESCRITORIO' "
                    "en Ene 2026, superando el umbral de 3 contratos/mes."
                ),
            }
        }
    )


# ---------------------------------------------------------------------------
# Paginated table response
# ---------------------------------------------------------------------------


class TablaContratosMenoresResponse(BaseModel):
    """Paginated wrapper returned by ``GET /api/contratos-menores/tabla``.

    Attributes:
        rows: The minor-contract rows for the requested page.
        total: Total number of matching rows (ignoring pagination).
        page: Current page number (1-based).
        page_size: Number of rows per page as requested.
    """

    rows: list[ContratoMenorResponse]
    total: int = Field(..., ge=0, description="Total de registros sin paginar.")
    page: int = Field(..., ge=1, description="Página actual (base 1).")
    page_size: int = Field(..., ge=1, description="Registros por página.")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "rows": [],
                "total": 84,
                "page": 1,
                "page_size": 20,
            }
        }
    )


# ---------------------------------------------------------------------------
# Forward-reference resolution
# ---------------------------------------------------------------------------
# ContratoMenorResponse references ContratoMenorProcesoResponse in its
# ``procesos`` field — rebuild the model after both classes are defined.

ContratoMenorResponse.model_rebuild()
