"""initial_schema

Revision ID: bc0da26fecd4
Revises: 
Create Date: 2026-02-17 17:09:47.571314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0da26fecd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificador_gasto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('tipo_generico', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=300), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=300), nullable=True),
    sa.Column('estado_rnp', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_table('registro_importacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formato', sa.String(length=50), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_username', sa.String(length=100), nullable=False),
    sa.Column('ue_sigla', sa.String(length=20), nullable=True),
    sa.Column('registros_ok', sa.Integer(), nullable=False),
    sa.Column('registros_error', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidad_ejecutora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('nivel', sa.String(length=10), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_presupuestal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('sec_funcional', sa.String(length=20), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modificacion_presupuestal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('clasificador_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nota_modificacion', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('pim_resultante', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['clasificador_id'], ['clasificador_gasto.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nombre_completo', sa.String(length=300), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actividad_operativa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_ceplan', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('oei', sa.String(length=200), nullable=True),
    sa.Column('aei', sa.String(length=200), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta_presupuestal.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adquisicion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('tipo_objeto', sa.String(length=20), nullable=True),
    sa.Column('tipo_procedimiento', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fase_actual', sa.String(length=50), nullable=True),
    sa.Column('monto_referencial', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monto_adjudicado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta_presupuestal.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('contrato_menor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('tipo_objeto', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('monto_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monto_ejecutado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('n_orden', sa.String(length=50), nullable=True),
    sa.Column('n_cotizaciones', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta_presupuestal.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('programacion_presupuestal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('clasificador_id', sa.Integer(), nullable=False),
    sa.Column('pia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pim', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('certificado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('compromiso_anual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('devengado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('girado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clasificador_id'], ['clasificador_gasto.id'], ),
    sa.ForeignKeyConstraint(['meta_id'], ['meta_presupuestal.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['unidad_ejecutora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adquisicion_detalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adquisicion_id', sa.Integer(), nullable=False),
    sa.Column('n_expediente', sa.String(length=50), nullable=True),
    sa.Column('n_proceso_seace', sa.String(length=50), nullable=True),
    sa.Column('n_proceso_pladicop', sa.String(length=50), nullable=True),
    sa.Column('bases_url', sa.String(length=500), nullable=True),
    sa.Column('resolucion_aprobacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_aprobacion_expediente', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adquisicion_id'], ['adquisicion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adquisicion_id')
    )
    op.create_table('adquisicion_proceso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adquisicion_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('hito', sa.String(length=200), nullable=False),
    sa.Column('fase', sa.String(length=50), nullable=True),
    sa.Column('area_responsable', sa.String(length=50), nullable=True),
    sa.Column('dias_planificados', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_real_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_real_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adquisicion_id'], ['adquisicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_menor_proceso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contrato_menor_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('hito', sa.String(length=200), nullable=False),
    sa.Column('area_responsable', sa.String(length=50), nullable=True),
    sa.Column('dias_planificados', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contrato_menor_id'], ['contrato_menor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programacion_mensual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programacion_presupuestal_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('programado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ejecutado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['programacion_presupuestal_id'], ['programacion_presupuestal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programacion_mensual')
    op.drop_table('contrato_menor_proceso')
    op.drop_table('adquisicion_proceso')
    op.drop_table('adquisicion_detalle')
    op.drop_table('programacion_presupuestal')
    op.drop_table('contrato_menor')
    op.drop_table('adquisicion')
    op.drop_table('actividad_operativa')
    op.drop_table('usuario')
    op.drop_table('modificacion_presupuestal')
    op.drop_table('meta_presupuestal')
    op.drop_table('alerta')
    op.drop_table('unidad_ejecutora')
    op.drop_table('registro_importacion')
    op.drop_table('proveedor')
    op.drop_table('clasificador_gasto')
    # ### end Alembic commands ###
