"""Alerta model — automated system alert for budget, procurement, and contract events."""

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class Alerta(Base):
    """Automated alert generated by business rule evaluation.

    Alerts are created by the alerts engine when thresholds are breached
    (e.g. budget deviation > 10%, procurement deadline exceeded). Each alert
    uses a generic polymorphic reference (entidad_id + entidad_tipo) to point
    to the source entity without hard foreign key constraints.

    Attributes:
        id: Primary key.
        tipo: Alert rule type identifier (one of 8 defined rule types).
        nivel: Severity — "ROJO" (critical), "AMARILLO" (warning), "VERDE" (info).
        titulo: Short human-readable alert title.
        descripcion: Detailed description including context and recommended action.
        ue_id: Optional FK to UnidadEjecutora (alerts can be unit-specific).
        modulo: Dashboard module that generated the alert.
        entidad_id: Polymorphic ID of the source entity.
        entidad_tipo: Type name of the source entity.
        leida: Whether the alert has been read by a user.
        resuelta: Whether the alert has been resolved.
        fecha_generacion: When the alert was generated (defaults to now).
        fecha_lectura: When the alert was first read (nullable).
        fecha_resolucion: When the alert was marked resolved (nullable).
    """

    __tablename__ = "alerta"

    id = Column(Integer, primary_key=True, autoincrement=True)
    tipo = Column(String(50), nullable=True)
    nivel = Column(String(10), nullable=True)  # "ROJO", "AMARILLO", "VERDE"
    titulo = Column(String(300), nullable=True)
    descripcion = Column(Text, nullable=True)
    ue_id = Column(Integer, ForeignKey("unidad_ejecutora.id"), nullable=True)
    modulo = Column(String(50), nullable=True)
    # "PRESUPUESTO", "ADQUISICIONES", "CONTRATOS_MENORES", "ACTIVIDADES_OPERATIVAS"
    entidad_id = Column(Integer, nullable=True)
    entidad_tipo = Column(String(50), nullable=True)
    # "adquisicion", "contrato_menor", "actividad_operativa", "programacion"
    leida = Column(Boolean, default=False, nullable=False)
    resuelta = Column(Boolean, default=False, nullable=False)
    fecha_generacion = Column(DateTime, default=func.now(), nullable=False)
    fecha_lectura = Column(DateTime, nullable=True)
    fecha_resolucion = Column(DateTime, nullable=True)

    # Relationships
    unidad_ejecutora = relationship(
        "UnidadEjecutora", back_populates="alertas", lazy="select"
    )
